//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSI.Packages.Extensiones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSI.Packages.Extensiones.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actividad {
            get {
                object obj = ResourceManager.GetObject("Actividad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add / Edit Variable.
        /// </summary>
        internal static string AddVariableFastKey {
            get {
                return ResourceManager.GetString("AddVariableFastKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap applycodechanges_6548 {
            get {
                object obj = ResourceManager.GetObject("applycodechanges_6548", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fix current object problems....
        /// </summary>
        internal static string ArreglarProblemas {
            get {
                return ResourceManager.GetString("ArreglarProblemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autocomplete.
        /// </summary>
        internal static string Autocomplete {
            get {
                return ResourceManager.GetString("Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Ayuda {
            get {
                object obj = ResourceManager.GetObject("Ayuda", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AyudaImg {
            get {
                object obj = ResourceManager.GetObject("AyudaImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using System;
        ///using GeneXus.Builder;
        ///using System.IO;
        ///
        ///public class %BLDASSEMBLIESNAME% : GxBaseBuilder
        ///{
        ///   string cs_path = &quot;.&quot; ;
        ///   
        ///   public %BLDASSEMBLIESNAME%( ) : base()
        ///   {
        ///   }
        ///
        ///   public override int BeforeCompile( )
        ///   {
        ///      return 0 ;
        ///   }
        ///
        ///   public override int AfterCompile( )
        ///   {
        ///      int ErrCode ;
        ///      ErrCode = 0 ;
        ///      if ( ! File.Exists(@&quot;bin\client.exe.config&quot;) || checkTime(@&quot;bin\client.exe.config&quot;,cs_path + @&quot;\client.exe.config&quot;) )
        ///      {
        ///         File.Co [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BldAssemblies_cs {
            get {
                return ResourceManager.GetString("BldAssemblies_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BreakpointEnabled_6584_16x {
            get {
                object obj = ResourceManager.GetObject("BreakpointEnabled_6584_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BreakpointsWindow_6557 {
            get {
                object obj = ResourceManager.GetObject("BreakpointsWindow_6557", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap build_Solution_16xLG {
            get {
                object obj = ResourceManager.GetObject("build_Solution_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check exportable objects.
        /// </summary>
        internal static string CheckExportableTW {
            get {
                return ResourceManager.GetString("CheckExportableTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Genexus build&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h1&gt;Genexus build&lt;/h1&gt;
        ///	    &lt;table&gt;
        ///	        &lt;tr&gt;
        ///	            &lt;td&gt;&lt;b&gt;KBase&lt;/b&gt;&lt;/td&gt;
        ///	            &lt;td&gt;&lt;a href=&quot;%KBASEPATH%&quot;&gt;%KBASEPATH%&lt;/a&gt;&lt;/td&gt;
        ///	        &lt;/tr&gt;
        ///	        &lt;tr&gt;
        ///	            &lt;td&gt;&lt;b&gt;Enviroment&lt;/b&gt;&lt;/td&gt;
        ///	            &lt;td&gt;&lt;a href=&quot;%ENVIRONMENTPATH%&quot;&gt;%ENVIROMENTDESCRIPTION%&lt;/a&gt;&lt;/td&gt;
        ///	        &lt;/tr&gt;
        ///	    &lt;/table&gt;
        ///	    
        ///        &lt;div&gt;%COMPILATIONLOG%&lt;/div&gt;        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CompilationEmailTemplate {
            get {
                return ResourceManager.GetString("CompilationEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Compile_191 {
            get {
                object obj = ResourceManager.GetObject("Compile_191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy objects info as table.
        /// </summary>
        internal static string CopyObjectsAsTable {
            get {
                return ResourceManager.GetString("CopyObjectsAsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy selected obj. parm rule to clipboard.
        /// </summary>
        internal static string CopyParmRule {
            get {
                return ResourceManager.GetString("CopyParmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to update record with SDT values....
        /// </summary>
        internal static string CrearProcActualizacionSdt {
            get {
                return ResourceManager.GetString("CrearProcActualizacionSdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to assign an attribute (P&lt;attribute&gt;)....
        /// </summary>
        internal static string CrearProcAsignarAtributo {
            get {
                return ResourceManager.GetString("CrearProcAsignarAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to delete record (P&lt;table&gt;Bor)....
        /// </summary>
        internal static string CrearProcBorradoRegistro {
            get {
                return ResourceManager.GetString("CrearProcBorradoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to load SDT from record....
        /// </summary>
        internal static string CrearProcCargaSdt {
            get {
                return ResourceManager.GetString("CrearProcCargaSdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to insert record (P&lt;table&gt;Gen)....
        /// </summary>
        internal static string CrearProcInsercion {
            get {
                return ResourceManager.GetString("CrearProcInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to insert record with SDT values....
        /// </summary>
        internal static string CrearProcInsercionSdt {
            get {
                return ResourceManager.GetString("CrearProcInsercionSdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create procedure to retrieve attribute (PU&lt;attribute&gt;)....
        /// </summary>
        internal static string CrearProcObtenerValor {
            get {
                return ResourceManager.GetString("CrearProcObtenerValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create SDT from table structure....
        /// </summary>
        internal static string CrearSdtDeTabla {
            get {
                return ResourceManager.GetString("CrearSdtDeTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CSharpProject_SolutionExplorerNode {
            get {
                object obj = ResourceManager.GetObject("CSharpProject_SolutionExplorerNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CustomActionsEditor_5850 {
            get {
                object obj = ResourceManager.GetObject("CustomActionsEditor_5850", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] data_info {
            get {
                object obj = ResourceManager.GetObject("data_info", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Diagram_8283 {
            get {
                object obj = ResourceManager.GetObject("Diagram_8283", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LSI.Extensions configuration....
        /// </summary>
        internal static string EditarConfiguracion {
            get {
                return ResourceManager.GetString("EditarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit object calls.
        /// </summary>
        internal static string EditCallsTW {
            get {
                return ResourceManager.GetString("EditCallsTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Executequery_9958 {
            get {
                object obj = ResourceManager.GetObject("Executequery_9958", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extract selected code to new Data Selector.
        /// </summary>
        internal static string ExtractDataSelector {
            get {
                return ResourceManager.GetString("ExtractDataSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon ExtractMethod_6786 {
            get {
                object obj = ResourceManager.GetObject("ExtractMethod_6786", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extract selected code to new Procedure.
        /// </summary>
        internal static string ExtractProcedure {
            get {
                return ResourceManager.GetString("ExtractProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Find_5650 {
            get {
                object obj = ResourceManager.GetObject("Find_5650", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormRunHS {
            get {
                object obj = ResourceManager.GetObject("FormRunHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Formula {
            get {
                object obj = ResourceManager.GetObject("Formula", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate prediction model.
        /// </summary>
        internal static string GenerateModel {
            get {
                return ResourceManager.GetString("GenerateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Add {
            get {
                object obj = ResourceManager.GetObject("Grid_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Build {
            get {
                object obj = ResourceManager.GetObject("Grid_Build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Check {
            get {
                object obj = ResourceManager.GetObject("Grid_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Delete {
            get {
                object obj = ResourceManager.GetObject("Grid_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Edit {
            get {
                object obj = ResourceManager.GetObject("Grid_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Refresh {
            get {
                object obj = ResourceManager.GetObject("Grid_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Run {
            get {
                object obj = ResourceManager.GetObject("Grid_Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_UpdateDB {
            get {
                object obj = ResourceManager.GetObject("Grid_UpdateDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hammer_Builder_16xLG {
            get {
                object obj = ResourceManager.GetObject("Hammer_Builder_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpVS {
            get {
                object obj = ResourceManager.GetObject("HelpVS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon HelpVSIco {
            get {
                object obj = ResourceManager.GetObject("HelpVSIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy table FOR EACH to clipboard....
        /// </summary>
        internal static string InsertarForEach {
            get {
                return ResourceManager.GetString("InsertarForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy table NEW to clipboard....
        /// </summary>
        internal static string InsertarNew {
            get {
                return ResourceManager.GetString("InsertarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export selected objects versioning info....
        /// </summary>
        internal static string KBSyncExportInfo {
            get {
                return ResourceManager.GetString("KBSyncExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Review objects versioning info on destination KB....
        /// </summary>
        internal static string KBSyncReviewInfo {
            get {
                return ResourceManager.GetString("KBSyncReviewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon LSI {
            get {
                object obj = ResourceManager.GetObject("LSI", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon LsiImport {
            get {
                object obj = ResourceManager.GetObject("LsiImport", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] model {
            get {
                object obj = ResourceManager.GetObject("model", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objects modified by users.
        /// </summary>
        internal static string ObjectsModifiedByUser {
            get {
                return ResourceManager.GetString("ObjectsModifiedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Objetos {
            get {
                object obj = ResourceManager.GetObject("Objetos", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LSI.Extensions documentation (v4.4.0).
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show parameter info.
        /// </summary>
        internal static string ParameterInfo {
            get {
                return ResourceManager.GetString("ParameterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste as GeneXus string literal.
        /// </summary>
        internal static string PasteAsStringLiteral {
            get {
                return ResourceManager.GetString("PasteAsStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Processing {
            get {
                object obj = ResourceManager.GetObject("Processing", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16xLG {
            get {
                object obj = ResourceManager.GetObject("refresh_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reorder winform tab control pages....
        /// </summary>
        internal static string ReorderWinTab {
            get {
                return ResourceManager.GetString("ReorderWinTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replace variables &apos;Attribute based on&apos; property....
        /// </summary>
        internal static string ReplaceVariablesAttributeBased {
            get {
                return ResourceManager.GetString("ReplaceVariablesAttributeBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check reports fonts....
        /// </summary>
        internal static string RevisarFuentes {
            get {
                return ResourceManager.GetString("RevisarFuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search on Genexus sources.
        /// </summary>
        internal static string SearchGxSources {
            get {
                return ResourceManager.GetString("SearchGxSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search main references.
        /// </summary>
        internal static string SearchMainTW {
            get {
                return ResourceManager.GetString("SearchMainTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search references.
        /// </summary>
        internal static string SearchReferencesTW {
            get {
                return ResourceManager.GetString("SearchReferencesTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search on Genexus sources.
        /// </summary>
        internal static string SearchSourcesTW {
            get {
                return ResourceManager.GetString("SearchSourcesTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search unreferenced objects.
        /// </summary>
        internal static string SearchUnreferencedTW {
            get {
                return ResourceManager.GetString("SearchUnreferencedTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Shortcut_8169 {
            get {
                object obj = ResourceManager.GetObject("Shortcut_8169", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap startwithoutdebugging_6556 {
            get {
                object obj = ResourceManager.GetObject("startwithoutdebugging_6556", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Strings_7959 {
            get {
                object obj = ResourceManager.GetObject("Strings_7959", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Symbols_Pause_16xLG {
            get {
                object obj = ResourceManager.GetObject("Symbols_Pause_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Table_748 {
            get {
                object obj = ResourceManager.GetObject("Table_748", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set max. winform size.
        /// </summary>
        internal static string TamMaximoWinform {
            get {
                return ResourceManager.GetString("TamMaximoWinform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check if transaction removal will reorganize database.
        /// </summary>
        internal static string VerificarBorradoTransaccion {
            get {
                return ResourceManager.GetString("VerificarBorradoTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check current object.
        /// </summary>
        internal static string VerificarObjeto {
            get {
                return ResourceManager.GetString("VerificarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check selected objects.
        /// </summary>
        internal static string VerifySelectedObjects {
            get {
                return ResourceManager.GetString("VerifySelectedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon WindowsForm_817 {
            get {
                object obj = ResourceManager.GetObject("WindowsForm_817", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon WindowsGroups_7309 {
            get {
                object obj = ResourceManager.GetObject("WindowsGroups_7309", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work with mains.
        /// </summary>
        internal static string WorkWithMains {
            get {
                return ResourceManager.GetString("WorkWithMains", resourceCulture);
            }
        }
    }
}
